networks:
  default:
    external:
      name: expenses
volumes:
  mysql:

services:
  # docker run -d --name mongodb --network=roboshop mongodb:1
  mysql:
    image: mysql:v1
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume
    # networks:
    # - roboshop

  

  backend:
    image: backend:v1
    container_name: backend
    depends_on:
    - mysql
    

  frontend:
    image: frontend:v1
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"

  