networks:
  default:
    external:
      name: expense
volumes:
  mysql:
services:
  mysql:
    #image: mysql:v1.0
    image: mutthu2512/mysql:v1
    container_name: mysql # --name mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ExpenseApp@1
      - MYSQL_USER=expense
      - MYSQL_PASSWORD=ExpenseApp@1
      - MYSQL_DATABASE=transactions
    volumes:
    - source: mysql
      target: /var/lib/mysql
      type: volume # -v volume-name:/path/in/container
  backend:
    #image: backend:v1.0
    image: mutthu2512/backend:v1
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js"
    depends_on: 
    - mysql
  frontend:
    #image: frontend:v1.0
    image: mutthu2512/frontend:v1
    container_name: frontend
    depends_on:
    - backend
    ports:
    - "80:80"